/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Antigravity-inspired dark system (Inspira-Grid brand)
        brand: {
          DEFAULT: '#6ee7ff',
          primary: '#6ee7ff',
          secondary: '#3dd6f5',
          light: '#a5f3fc',
          dark: '#22d3ee',
          50: '#ecfeff',
          100: '#cffafe',
          200: '#a5f3fc',
          300: '#67e8f9',
          400: '#6ee7ff',
          500: '#22d3ee',
          600: '#06b6d4',
          700: '#0891b2',
          800: '#0e7490',
          900: '#155e75',
        },
        accent: {
          purple: '#a78bfa',
          blue: '#60a5fa',
          green: '#34d399',
          orange: '#fbbf24',
          pink: '#f472b6',
          cyan: '#6ee7ff',
          emerald: '#34d399',
          amber: '#fbbf24',
        },
        dark: {
          DEFAULT: '#050505',
          darker: '#000000',
          lighter: '#0a0a0a',
          card: '#111111',
          surface: '#0a0a0a',
          border: '#1f1f1f',
          hover: '#161616',
        },
        text: {
          primary: '#f5f2eb',
          secondary: '#c4bfb5',
          tertiary: '#7a756c',
          quaternary: '#5c574f',
          muted: '#5c574f',
        },
        success: {
          DEFAULT: '#34d399',
          light: '#6ee7b7',
          dark: '#059669',
          50: '#ecfdf5',
          100: '#d1fae5',
          500: '#34d399',
          600: '#059669',
        },
        warning: {
          DEFAULT: '#fbbf24',
          light: '#fcd34d',
          dark: '#d97706',
          50: '#fffbeb',
          100: '#fef3c7',
          500: '#fbbf24',
          600: '#d97706',
        },
        danger: {
          DEFAULT: '#f87171',
          light: '#fca5a5',
          dark: '#dc2626',
          50: '#fef2f2',
          100: '#fee2e2',
          500: '#f87171',
          600: '#dc2626',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        display: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
        mono: [
          'JetBrains Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.05' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '0.95' }],
        '8xl': ['6rem', { lineHeight: '0.92' }],
        '9xl': ['8rem', { lineHeight: '0.9' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '0.75rem',
        '2xl': '1rem',
      },
      boxShadow: {
        'ig-focus': '0 0 0 2px #050505, 0 0 0 4px #6ee7ff',
        'ig-glow': '0 0 24px rgba(110, 231, 255, 0.15)',
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out',
        'fade-in-up': 'fadeInUp 0.45s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
      screens: {
        xs: '475px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
        '3xl': '1920px',
      },
      spacing: {
        18: '4.5rem',
        88: '22rem',
        112: '28rem',
        128: '32rem',
      },
    },
  },
  plugins: [],
};
